version: "3.7"

services:
  # Define a service named minio
  minio:
    # Usa a imagem do MinIO no Quay.io
    image: quay.io/minio/minio:RELEASE.2024-01-13T07-53-03Z-cpuv1
    # Define o Comando de inicio do servidor do Minio
    command: server /data --console-address ":9001"
    # Define a rede que o container vai usar
    networks:
      - network_public
    # Define o volume que irá armazenar os dados do minio
    volumes:
      - minio_data:/data
    # Define as variaveis de ambiente que o container vai usar
    environment:
      # Define o usuario root do Minio
      - MINIO_ROOT_USER=admin
      # Define a senha root do Minio
      - MINIO_ROOT_PASSWORD=Mfcd62!!Mfcd62!!
      # Define o endereço do console do Minio
      - MINIO_BROWSER_REDIRECT_URL=https://minio.octhost.com.br
      # Define o endereço público do Minio
      - MINIO_SERVER_URL=https://s3.octhost.com.br
    deploy:
      # Define o modo de deploy do container
      mode: replicated
      # Define o numero de replicas do container (sempre 1)
      replicas: 1
      # Define o local de execução do container
      placement:
        constraints:
          - node.role == manager
      labels:
        # Habilita o Traefik
        - traefik.enable=true
        # Define o endereço publico do Minio
        - traefik.http.routers.minio_public.rule=Host(`s3.octhost.com.br`)
        # Redireciona o endereço para HTTPS
        - traefik.http.routers.minio_public.entrypoints=websecure
        # Define o certificado SSL
        - traefik.http.routers.minio_public.tls.certresolver=letsencryptresolver
        # Define a porta do servidor publico do Minio
        - traefik.http.services.minio_public.loadbalancer.server.port=9000
        # Define os Headers que o Minio vai usar
        - traefik.http.services.minio_public.loadbalancer.passHostHeader=true
        # Define o serviço que irá ser usado
        - traefik.http.routers.minio_public.service=minio_public
        # Define o endereço do console do Minio
        - traefik.http.routers.minio_console.rule=Host(`minio.octhost.com.br`)
        # Redireciona o endereço para HTTPS
        - traefik.http.routers.minio_console.entrypoints=websecure
        # Define o certificado SSL
        - traefik.http.routers.minio_console.tls.certresolver=letsencryptresolver
        # Define a porta do servidor do console do Minio
        - traefik.http.services.minio_console.loadbalancer.server.port=9001
        # Define os Headers que o Minio vai usar
        - traefik.http.services.minio_console.loadbalancer.passHostHeader=true
        # Define o serviço que irá ser usado
        - traefik.http.routers.minio_console.service=minio_console

volumes:
  minio_data:
    external: true
    name: minio_data

networks:
  network_public:
    external: true
    name: network_public
