version: "3.7"

services:
  # Define a serviço builder
  typebot_builder:
    # Usa a imagem do Typebot Builder
    image: baptistearno/typebot-builder:3.3.0
    # Define a rede que o container vai usar
    networks:
      - network_public
    # Define as variaveis de ambiente que o container vai usar
    environment:
      #Configurações do banco de dados
      - DATABASE_URL=postgresql://postgres:Mfcd62!!Mfcd62!!@postgres:5432/typebot
      # Configurações de Criptografia de Cookies
      - ENCRYPTION_SECRET=7/l2NKGhkMUHRV0dt/g8hD2YNopCrAeH
      # Configurações do Plano do Typebot
      - DEFAULT_WORKSPACE_PLAN=UNLIMITED
      # Configura o endereço público do editor do Typebot
      - NEXTAUTH_URL=https://fluxo.octhost.com.br
      # Configura o endereço público do viewer do Typebot
      - NEXT_PUBLIC_VIEWER_URL=https://fluxoapi.octhost.com.br
      # Configura o endereço interno do Typebot
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      # Configurações para Habilitar / Desabilitar Criação de Contas
      - DISABLE_SIGNUP=false
      # Configurações do Typebot e SMTP
      - ADMIN_EMAIL=suporte@chattbot.com.br
      # Configurações do SMTP
      - NEXT_PUBLIC_SMTP_FROM='Typebot' <suporte@chattbot.com.br>
      - SMTP_AUTH_DISABLED=false
      - SMTP_USERNAME=suporte@chattbot.com.br
      - SMTP_PASSWORD=LB,#&5r1cs(*x[Fe
      - SMTP_HOST=mail.chattbot.com.br
      - SMTP_PORT=465
      - SMTP_SECURE=true
      # Configurações do Typebot e Google Cloud
      #- GOOGLE_CLIENT_ID=
      #- GOOGLE_CLIENT_SECRET=
      #- NEXT_PUBLIC_GOOGLE_API_KEY=
      # Configurações do Typebot e Minio
      - S3_ACCESS_KEY=Vw9ZAO8MeOVTTEBTL8Va
      - S3_SECRET_KEY=splY4LNVWp8Uiiht50519LvRUuoIj2lrBiWQciIZ
      - S3_BUCKET=typebot
      - S3_ENDPOINT=s3.octhost.com.br
    deploy:
      # Define o modo de deploy do container
      mode: replicated
      # Define o numero de replicas do container (sempre 1)
      replicas: 1
      # Define o local de execução do container
      placement:
        constraints:
          - node.role == manager
          # - node.hostname == worker1
      resources:
        limits:
          # Define a quantidade de CPU para o Typebot para evitar travamento do Host
          cpus: "1"
          # Define a quantidade de RAM para o Typebot para evitar travamento do Host
          memory: 1024M
      labels:
        # Habilita o Traefik
        - traefik.enable=true
        # Define o endereço publico do Typebot
        - traefik.http.routers.typebot_builder.rule=Host(`fluxo.octhost.com.br`)
        # Redireciona o endereço para HTTPS
        - traefik.http.routers.typebot_builder.entrypoints=websecure
        # Define o certificado SSL
        - traefik.http.routers.typebot_builder.tls.certresolver=letsencryptresolver
        # Define a porta do servidor publico do Typebot
        - traefik.http.services.typebot_builder.loadbalancer.server.port=3000
        # Define os Headers que o Typebot vai usar
        - traefik.http.services.typebot_builder.loadbalancer.passHostHeader=true
        # Define o serviço que irá ser usado
        - traefik.http.routers.typebot_builder.service=typebot_builder
networks:
  network_public:
    external: true
    name: network_public
